### ISSUE TITLE
Add dependency on "streaming" package.

### ISSUE THREAD

**Issue by danidiaz** [danidiaz/pipes-transduce#3]
And provide the following Stream-consuming functions.

- withStreamCont :: (Stream (Of b) IO () -> IO a) -> Fold1 b e a	 

- withStreamCont' :: (forall r. Stream (Of b) IO r -> IO (a, r)) -> Fold1 b e a	 

- withFallibleStreamCont :: (Stream (Of b) IO () -> IO (Either e a))	-> Fold1 b e a	 

- withFallibleStreamCont' :: (forall r. Stream (Of b) IO r -> IO (Either e (a, r))) -> Fold1 b e a

**Comment by ocramz** [comment]
I just came here to ask exactly for this. Thanks!

**Comment by danidiaz** [comment]
The functions have been added in version 0.4.3.2. The functions convert the `Stream`s to `Producer`s internally, so there will be an overhead.

Mind if I ask how are you using `pipes-transduce`, if you are using it? Just curious.

**Comment by ocramz** [comment]
Ah, very simply I have a project that uses `streaming`-based IO, and I would like to compose reductions over it using `foldl`.

**Comment by danidiaz** [comment]
Be aware that, in many cases, it's simpler to compose `foldl` folds directly through their `Applicative` instances, and then use them to consume the `Stream`s by way of [purely and impurely](http://hackage.haskell.org/package/streaming-0.2.1.0/docs/Streaming-Prelude.html#g:7).

Another method of consuming the same stream in two ways is by using [copy](https://stackoverflow.com/questions/49122127/how-to-track-progress-through-a-streaming-bytestring/49124865#49124865).

This package only buys you something if, for example, you want each way of consuming the stream to have its own "bracketing context".
